# Generated by Django 3.1.3 on 2020-11-18 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='birthday',
            new_name='birth_date',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='surname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='registration',
            new_name='registration_date',
        ),
    ]
